import { defineStore } from "pinia";

export const useCounterStore = defineStore("counter", {
  state: () => ({
    testimonials: [
      {
        id: 1,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-1.jpg",
        name: "Client Name",
        state: "Profession",
        rate: "5",
      },
      {
        id: 2,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-2.webp",
        name: "Client Name",
        state: "Profession",
        rate: "4",
      },
      {
        id: 3,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-3.webp",
        name: "Client Name",
        state: "Profession",
        rate: "4.5",
      },
      {
        id: 4,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-4.jpg",
        name: "Client Name",
        state: "Profession",
        rate: "3.5",
      },
      {
        id: 5,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-5.webp",
        name: "Client Name",
        state: "Profession",
        rate: "3",
      },
      {
        id: 6,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-6.webp",
        name: "Client Name",
        state: "Profession",
        rate: "4",
      },
      {
        id: 7,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-7.avif",
        name: "Client Name",
        state: "Profession",
        rate: "5",
      },
      {
        id: 8,
        desc: "Lorem Ipsum is simply dummy text of the printing Ipsum has been the industry's standard dummy text ecer since the 1500s",
        img: "/images/person-8.avif",
        name: "Client Name",
        state: "Profession",
        rate: "4.5",
      },
    ],
    products: [
      {
        id: 0,
        img: "/images/apple.avif",
        title: "Apple",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.99 / kg",
      },
      {
        id: 1,
        img: "/images/graps.jpeg",
        title: "Graps",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.55 / kg",
      },
      {
        id: 2,
        img: "/images/strawbery.jpg",
        title: "Strewbery",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$3.99 / kg",
      },
      {
        id: 3,
        img: "/images/apricot.jpg",
        title: "Apricot",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$3.89/ kg",
      },
      {
        id: 4,
        img: "/images/Banana.jpg",
        title: "Banana",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$5.99 / kg",
      },
      {
        id: 5,
        img: "/images/orange.jpg",
        title: "Orange",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$5.50 / kg",
      },
      {
        id: 6,
        img: "/images/berries.webp",
        title: "Berries",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.30 / kg",
      },
      {
        id: 7,
        img: "/images/mango.webp",
        title: "Mango",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$6.99 / kg",
      },
      {
        id: 8,
        img: "/images/blueberry.jfif",
        title: "Blueberry",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.99 / kg",
      },
      {
        id: 9,
        img: "/images/cucumber.webp",
        title: "Cucmber",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.99 / kg",
      },
      {
        id: 10,
        img: "/images/broccoli.jpg",
        title: "Broccoli",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.55 / kg",
      },
      {
        id: 11,
        img: "/images/potatos.webp",
        title: "Potatos",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$3.99 / kg",
      },
      {
        id: 12,
        img: "/images/mint.jpg",
        title: "Mint",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$3.89/ kg",
      },
      {
        id: 13,
        img: "/images/thyme.webp",
        title: "Thyme",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$5.99 / kg",
      },
      {
        id: 14,
        img: "/images/tomato.avif",
        title: "Tomato",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$5.50 / kg",
      },
      {
        id: 15,
        img: "/images/Onion.jpg",
        title: "Onion",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.30 / kg",
      },
      {
        id: 16,
        img: "/images/Carrot.webp",
        title: "Carrot",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$6.99 / kg",
      },
      {
        id: 17,
        img: "/images/Lettuce.jpg",
        title: "Lettuce",
        desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus inventore recusandae eum quibusdam.",
        price: "$4.99 / kg",
      },
    ],
  }),
});
